{{- if $.Values.base.externalSecrets }}
{{- range $secret := $.Values.base.externalSecrets }}
{{- if ($secret.inject).enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "helper.fullname" (merge . $) }}
  namespace: {{ $.Release.Namespace }}
  {{- if or $.Values.base.labels.all $.Values.base.labels.secrets .labels }}
  labels:
  {{- (include "helper.labels" $) | nindent 4 }}
  {{- with .labels }}
  {{- toYaml . | nindent 4}}
  {{- end }}
  {{- with $.Values.base.labels.secrets }}
  {{- toYaml . | nindent 4}}
  {{- end }}
  {{- end }}
  {{- if or $.Values.base.labels.all $.Values.base.labels.secrets .annotations }}
  annotations:
  {{- (include "helper.annotations" $) | nindent 4 }}
  {{- with $.Values.base.annotations.secrets }}
  {{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .annotations }}
  {{- toYaml . | nindent 4}}
  {{- end }}
  {{- end }}
spec:
  refreshInterval: {{ default "60m" $secret.refreshInterval }}
  secretStoreRef:
    name: {{ required "SecretStoreRef not provided" $secret.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "helper.fullname" . }}
    creationPolicy: Owner
  {{- if ($secret.inject).enabled }}
    {{- if $secret.inject.dataFrom }}
  dataFrom:
  - extract:
      key: {{ required "secret Key not provided in externalSecrets" $secret.inject.dataFrom.secretKey }}
    {{- else if $secret.inject.data }}
  data:
      {{- range $secret.inject.data }}
  - secretKey: {{ .secretKey  }} 
    remoteRef:
      key: {{ .remoteRef.key }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- else if ($secret.volumeMount).enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "helper.fullname" (merge . $) }}
  namespace: {{ $.Release.Namespace }}
  {{- if or $.Values.base.labels.all $.Values.base.labels.secrets .labels }}
  labels:
  {{- (include "helper.labels" $) | nindent 4 }}
  {{- with .labels }}
  {{- toYaml . | nindent 4}}
  {{- end }}
  {{- with $.Values.base.labels.secrets }}
  {{- toYaml . | nindent 4}}
  {{- end }}
  {{- end }}
  {{- if or $.Values.base.labels.all $.Values.base.labels.secrets .annotations }}
  annotations:
  {{- (include "helper.annotations" $) | nindent 4 }}
  {{- with $.Values.base.annotations.secrets }}
  {{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .annotations }}
  {{- toYaml . | nindent 4}}
  {{- end }}
  {{- end }}
spec:
  refreshInterval: {{ default "60m" $secret.refreshInterval }}
  secretStoreRef:
    name: {{ required "SecretStoreRef not provided" $secret.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "helper.fullname" . }}
    creationPolicy: Owner
  data:
      {{- range $secret.volumeMount.data }}
  - secretKey: {{ .fileName }}
    remoteRef:
      key: {{ .secretKey  }}
      {{- end }}
{{- end }}
{{- end }}  
{{- end }}  