namespace: prod

helmGlobals:
  chartHome: ./../../../../k8s/

helmCharts:
  - name: application-helm-chart
    releaseName: ai-service
    valuesFile: ./values.yaml
    namespace: prod
    additionalValuesFiles:
      - "../../base/base.yaml"
      - "../global/global.yaml"
